### ISSUE TITLE
standard logging integration

### ISSUE THREAD

**Issue by dcwatson** [imsweb/django-graylog#3]
It might be nice to have a custom logging.Handler class that can access some thread-local current request, so that any messages logged via normal Python logging can be correlated to a request. This would be especially helpful in third-party code that is unaware of requests.

**Comment by kukwaa** [comment]
Here's some experimental work on such a feature:

Creating a logger, adding a graylog socket handler, and sending a message:
https://git.imsweb.com/web/dcp/cdas/cdas/-/blob/d5bf36ee6402de757f19992635e4128b191bce0f/cdas/management/commands/temp/graylog_test.py#L68
 
SocketHandler class:
https://git.imsweb.com/web/dcp/cdas/cdas/-/blob/d5bf36ee6402de757f19992635e4128b191bce0f/cdas/utils/graylog.py#L24

**Comment by dcwatson** [comment]
0.7 has been released to PyPI with this.
